

Logs new start


Logs new start


Logs new start

New error in creating request at 2021-04-24 16:49:56.576579:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:49:57.263197:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:06.398836:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:07.066337:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:16.523142:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:17.202436:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:26.894077:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:27.582313:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:36.721070:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:37.400230:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:46.523924:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:47.222361:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:56.650694:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:57.336040:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:06.610970:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:07.334344:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:16.552076:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:17.252602:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:26.656140:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:27.375153:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:36.654654:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:37.344321:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:46.707478:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:47.407044:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:56.693511:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:57.397217:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:52:06.680056:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:52:07.382828:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:52:16.735254:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:52:17.375036:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:52:26.638754:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:52:27.277556:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:52:36.756512:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:52:37.516246:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:52:46.797937:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start

New error in creating request at 2021-04-25 18:24:57.737887:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:24:58.474711:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:07.849684:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:11.884163:
type - <class 'TypeError'>, name - createRequest.py, line - 96, error - Expected discord.Colour, int, or Embed.Empty but received str instead.

New error in creating request at 2021-04-25 18:25:12.066469:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:17.689697:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:18.301532:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:24.623969:
type - <class 'TypeError'>, name - createRequest.py, line - 96, error - Expected discord.Colour, int, or Embed.Empty but received str instead.

New error in creating request at 2021-04-25 18:25:27.549850:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:28.154658:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:37.512106:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:38.148946:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:47.498754:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:48.112590:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:57.723300:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:58.407840:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:07.552022:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:08.223267:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:17.608817:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:18.284691:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:26.585237:
type - <class 'TypeError'>, name - createRequest.py, line - 96, error - Expected discord.Colour, int, or Embed.Empty but received str instead.

New error in creating request at 2021-04-25 18:26:27.594990:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:28.213095:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:37.558827:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:38.147057:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:47.575545:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:48.201295:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:57.667722:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:58.317632:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 18:27:26.731780:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:27:27.410965:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 18:29:27.555786:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:29:28.215516:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:29:37.754692:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:29:38.960365:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:29:48.878035:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:29:49.516743:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:29:58.902755:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:29:59.527124:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:08.650609:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:11.496799:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:20.075839:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:20.757711:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:27.858261:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:28.476450:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:37.693639:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:38.877661:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:47.789770:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:48.482221:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:57.786928:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:58.416097:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 18:33:31.867294:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:33:32.601634:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:33:42.373084:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:33:43.553955:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 20:50:18.883923:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:50:19.643289:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:50:28.627200:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:50:29.297347:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:50:38.798366:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:50:39.468025:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:50:48.944592:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:50:49.602656:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:50:58.669726:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:50:59.301340:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:51:08.777051:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:51:09.440955:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:51:18.881288:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:51:19.650948:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:51:29.003854:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:51:29.729954:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:51:38.974324:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:51:39.665249:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 20:52:18.506443:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:52:19.146565:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:52:28.986647:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:52:29.635371:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:52:38.181333:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:52:38.902345:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 20:53:08.709597:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:53:09.468199:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:53:18.814871:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:53:19.453108:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:53:28.597627:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:53:29.266275:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:53:38.544998:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:53:39.249953:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 20:53:48.661319:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 20:53:49.325925:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 21:11:59.617534:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:12:00.298412:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:12:09.547378:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:12:10.213122:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 21:12:36.816164:
type - <class 'discord.errors.NotFound'>, name - helpCommand.py, line - 24, error - 404 Not Found (error code: 10008): Unknown Message


Logs new start

New error in creating request at 2021-04-25 21:16:36.283749:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:16:36.981612:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 21:18:36.130779:
type - <class 'discord.errors.NotFound'>, name - helpCommand.py, line - 24, error - 404 Not Found (error code: 10008): Unknown Message

New error in creating request at 2021-04-25 21:18:43.171985:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:18:43.822012:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:18:53.206346:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:18:53.868575:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 21:19:50.498197:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:19:51.218289:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 21:20:38.886677:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:20:39.631808:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:20:48.777326:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:20:49.481000:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 21:21:49.242631:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:21:49.881980:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:21:59.121392:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:22:00.474605:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:22:09.700322:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:22:10.376230:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:22:19.291469:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:22:20.038952:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:22:29.327940:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:22:30.018667:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:22:39.294972:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:22:40.004397:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 21:23:20.874988:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:23:21.520658:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:23:30.750921:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:23:31.501811:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:23:40.606756:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:23:41.229844:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:23:50.622868:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:23:51.327269:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:24:00.799759:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:24:01.453329:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:24:10.837178:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:24:11.525510:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:24:20.828124:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:24:21.564452:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:24:30.848152:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:24:31.690917:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:24:40.869453:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:24:41.635574:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:24:50.786570:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:24:51.495067:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:25:00.864451:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:25:11.939704:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:25:13.382632:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:25:14.125565:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:25:26.548997:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:25:27.222622:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:25:30.867890:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:25:31.539806:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:25:40.857200:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:25:41.515152:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:25:50.834011:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:25:51.506456:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:26:00.947331:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:26:01.592387:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:26:10.802410:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:26:11.481332:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 21:26:20.796394:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 21:26:21.468848:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start
