

Logs new start


Logs new start


Logs new start

New error in creating request at 2021-04-24 16:49:56.576579:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:49:57.263197:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:06.398836:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:07.066337:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:16.523142:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:17.202436:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:26.894077:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:27.582313:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:36.721070:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:37.400230:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:46.523924:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:47.222361:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:50:56.650694:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:50:57.336040:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:06.610970:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:07.334344:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:16.552076:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:17.252602:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:26.656140:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:27.375153:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:36.654654:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:37.344321:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:46.707478:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:47.407044:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:51:56.693511:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:51:57.397217:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:52:06.680056:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:52:07.382828:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:52:16.735254:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:52:17.375036:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:52:26.638754:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:52:27.277556:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:52:36.756512:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-24 16:52:37.516246:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-24 16:52:46.797937:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start

New error in creating request at 2021-04-25 18:24:57.737887:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:24:58.474711:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:07.849684:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:11.884163:
type - <class 'TypeError'>, name - createRequest.py, line - 96, error - Expected discord.Colour, int, or Embed.Empty but received str instead.

New error in creating request at 2021-04-25 18:25:12.066469:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:17.689697:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:18.301532:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:24.623969:
type - <class 'TypeError'>, name - createRequest.py, line - 96, error - Expected discord.Colour, int, or Embed.Empty but received str instead.

New error in creating request at 2021-04-25 18:25:27.549850:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:28.154658:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:37.512106:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:38.148946:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:47.498754:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:48.112590:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:25:57.723300:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:25:58.407840:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:07.552022:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:08.223267:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:17.608817:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:18.284691:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:26.585237:
type - <class 'TypeError'>, name - createRequest.py, line - 96, error - Expected discord.Colour, int, or Embed.Empty but received str instead.

New error in creating request at 2021-04-25 18:26:27.594990:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:28.213095:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:37.558827:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:38.147057:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:47.575545:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:48.201295:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:26:57.667722:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:26:58.317632:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 18:27:26.731780:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:27:27.410965:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 18:29:27.555786:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:29:28.215516:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:29:37.754692:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:29:38.960365:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:29:48.878035:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:29:49.516743:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:29:58.902755:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:29:59.527124:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:08.650609:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:11.496799:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:20.075839:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:20.757711:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:27.858261:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:28.476450:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:37.693639:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:38.877661:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:47.789770:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:48.482221:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:30:57.786928:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:30:58.416097:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-04-25 18:33:31.867294:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:33:32.601634:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-04-25 18:33:42.373084:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-04-25 18:33:43.553955:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'
