

Logs new start


Logs new start


Logs new start


Logs new start


Logs new start

New error in creating request at 2021-05-05 17:07:15.351816:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:07:16.029592:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:07:25.428335:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:07:26.072462:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:07:35.372377:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:07:35.986618:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:07:45.346683:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:07:46.057964:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error in creating request at 2021-05-05 17:08:04.688022:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:08:05.345121:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:08:14.205976:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:08:14.855572:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:08:24.110536:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:08:24.769426:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:08:34.098944:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:08:34.730250:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:08:44.197960:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:08:44.835596:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:08:54.100325:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:08:54.774932:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:09:04.128023:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:09:04.797680:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:09:14.130268:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:09:14.813628:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:09:24.111720:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:09:24.882321:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:09:34.176140:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:09:34.866785:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:09:44.180796:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:09:44.792509:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:09:54.200293:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:09:54.832674:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:10:04.275013:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:10:04.931445:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:10:14.164781:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:10:14.795810:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:10:24.331119:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:10:25.012622:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:10:34.184878:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:10:34.828981:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:10:44.286446:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:10:44.971387:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error in creating request at 2021-05-05 17:10:54.147263:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error in creating request at 2021-05-05 17:10:54.775056:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start
[<Role id=346775939105161247 name='@everyone'>, <Role id=346778168293851137 name='Nightbot'>, <Role id=770801839427158036 name='SuperModers'>, <Role id=770995156891205633 name='Конеко'>, <Role id=770995628909002764 name='Рыцари осуждения'>, <Role id=771023652903714826 name='Twitch Subscriber'>, <Role id=771023652903714827 name='Twitch Subscriber: Tier 1'>, <Role id=771023652903714828 name='Twitch Subscriber: Tier 2'>, <Role id=771023652903714829 name='Twitch Subscriber: Tier 3'>, <Role id=771029540650614817 name='Bot'>, <Role id=771045634814771221 name='💰Шейх'>, <Role id=771702030997782560 name='Streamer'>, <Role id=772099669680586784 name='Королева'>, <Role id=774284038155796490 name='Мятный Барон'>, <Role id=774476708585275432 name='Гача качок'>, <Role id=774751022811578369 name='Любитель лолей'>, <Role id=774752289008648232 name='Главный по мемам'>, <Role id=775045565078568960 name='Лоровед'>, <Role id=780492893999726643 name='Любитель милф'>, <Role id=781353733107220490 name='Последователь Дилюка'>, <Role id=781356315045396531 name='Последователь Кэ Цин'>, <Role id=781357751229612033 name='Адепт Мудрая Сова'>, <Role id=781357930901012520 name='Адепт Громовой Стилет'>, <Role id=783061799771045948 name='Кардинал Рассвета'>, <Role id=783792684380717108 name='Можно говорить'>, <Role id=785570523584135238 name='Спартак S1'>, <Role id=788091289090261072 name='Баянист'>, <Role id=790900065161969683 name='Бард'>, <Role id=791013889692139590 name='Киноманы'>, <Role id=793839851333877763 name='Красный'>, <Role id=793840052778172427 name='Розовый'>, <Role id=793840406261268531 name='Малиновый'>, <Role id=793840707004661800 name='Фиолетовый'>, <Role id=793840893605445635 name='Оранжевый'>, <Role id=793841068067127327 name='Золотой'>, <Role id=793841247734857778 name='Персиковый'>, <Role id=793841412906680341 name='Синий'>, <Role id=793841888879837194 name='Зеленый'>, <Role id=793841967150399529 name='Салатовый'>, <Role id=793842156371836939 name='Аква'>, <Role id=793842472026767390 name='Коричневый'>, <Role id=793842833974493184 name='Серебряный'>, <Role id=794001054165368902 name='Маджента'>, <Role id=795815343179431976 name='Аристократ'>, <Role id=796107141843779615 name='Горящий хиличурл'>, <Role id=796107296840613928 name='Златовласка'>, <Role id=796107431443824661 name='Элементалист'>, <Role id=796107616963133481 name='Пустой S1'>, <Role id=796107936249806858 name='Милашный Симп'>, <Role id=796108119183982632 name='Сексуальный Симп'>, <Role id=796489572896079984 name='Ticket Tool'>, <Role id=797837941472362537 name='Пати Мейкер'>, <Role id=797952633163612170 name='Лютик'>, <Role id=798782667554160681 name='April'>, <Role id=799411255949393952 name='carl-bot'>, <Role id=799419044108566568 name='Мут (временный бан)'>, <Role id=801268332409913415 name='Usagi chan'>, <Role id=801915486828232725 name='Спартак S2'>, <Role id=802145906413010967 name='Statbot'>, <Role id=802330222393425931 name='🐳Китёнок'>, <Role id=802569588658929764 name='Гайдодел'>, <Role id=803947134167678987 name='Koneko Guard'>, <Role id=805820191267094530 name='Ножки'>, <Role id=806272481177763840 name='ЭкстраКек 1s'>, <Role id=810228843477991444 name='Гомункул'>, <Role id=810229339664678922 name='Глупик'>, <Role id=810229945321521183 name='Кадр'>, <Role id=810230331855994890 name='Купидон'>, <Role id=810837451378524191 name='Мудрец'>, <Role id=812821133169917972 name='Принц'>, <Role id=812990310027231262 name='Вознесенный'>, <Role id=812991004679471115 name='Коронованный'>, <Role id=813175168842727454 name='Белый'>, <Role id=813737010388664351 name='Спартак S3'>, <Role id=815235813881020418 name='Зеленый Фонарь'>, <Role id=816054416632840202 name='Фейкодел'>, <Role id=820964447353962516 name='Художник'>, <Role id=821297593811206196 name='Рисует как Вермеер'>, <Role id=821297798116802582 name='Шутит как Ху Тао'>, <Role id=823180070713557024 name='Сливка'>, <Role id=823993997973389322 name='Гнилая слива'>, <Role id=826389875154616342 name='Поэт ветряных цветов'>, <Role id=832224496068198430 name='Товарищ'>, <Role id=838337704479555624 name='Пустой S2'>]


Logs new start

New error at 2021-05-14 15:08:17.460740:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-14 15:08:18.202744:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error at 2021-05-14 15:09:02.258768:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-14 15:09:02.947766:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-14 15:09:12.376016:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-14 15:09:13.194054:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-14 15:09:22.260205:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-14 15:09:23.176246:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error at 2021-05-25 16:32:22.848098:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:32:23.550349:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:32:33.409211:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:32:34.588798:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:32:42.976127:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:32:43.797072:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:32:53.245656:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:32:53.949160:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:33:02.901586:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:33:03.617969:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:33:12.829347:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:33:13.558142:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:33:22.979800:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:33:23.737861:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:33:33.491189:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:33:34.181213:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:33:42.840825:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:33:43.484480:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:33:53.054767:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:33:53.758560:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:34:03.537887:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:34:04.305550:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:34:13.049961:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:34:13.853868:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:34:23.140272:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list


Logs new start

New error at 2021-05-25 16:35:40.898528:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:35:41.653021:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:35:50.732137:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:35:51.391216:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:36:00.926105:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:36:01.862151:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:36:10.958050:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:36:11.758282:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:36:20.966148:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:36:21.690195:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:36:31.001067:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:36:31.683637:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:36:40.706231:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:36:41.392850:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:36:50.994134:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:36:51.658131:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:37:00.784532:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:37:01.505092:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:37:10.776216:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:37:11.489992:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:37:21.652866:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:37:22.431023:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:37:30.808929:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:37:31.487129:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:37:40.952527:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:37:41.759967:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:37:50.978410:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:37:51.740058:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:38:00.847335:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:38:01.557870:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:38:10.805172:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:38:11.707471:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error at 2021-05-25 16:38:52.339179:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:38:53.086370:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:39:03.753106:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:39:05.464283:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:39:12.497837:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:39:13.246095:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:39:22.453035:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:39:23.178516:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:39:32.760408:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:39:33.474713:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:39:42.519848:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:39:43.217915:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:39:52.454973:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:39:53.685162:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:40:02.653180:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:40:03.380352:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:40:12.730986:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:40:13.401791:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:40:22.773825:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:40:23.398808:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:40:32.708037:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:40:33.424002:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:40:42.532656:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:40:43.236619:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:40:52.609743:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:40:53.305377:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:41:02.651226:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:41:03.584878:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:41:12.709984:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:41:13.380777:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:41:22.780300:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:41:23.435065:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:41:32.604178:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:41:33.282412:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:41:42.711344:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:41:43.428900:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:41:52.593321:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:41:53.266997:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:42:02.739082:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:42:03.485629:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:42:12.551099:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:42:13.250334:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:42:22.807060:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:42:23.585910:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error at 2021-05-25 16:42:40.808983:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:42:41.465139:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 16:42:50.969973:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 16:42:51.700538:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error at 2021-05-25 17:12:08.899085:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:12:09.604136:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:12:18.844718:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:12:19.627720:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:12:29.002974:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:12:29.841982:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:12:39.112284:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:12:39.881282:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:12:49.074928:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:12:49.783928:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:12:58.914305:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:12:59.626309:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error at 2021-05-25 17:14:16.593416:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:14:17.373418:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:14:26.632226:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:14:27.462753:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:14:36.645772:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:14:37.811294:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:14:46.416828:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:14:47.145870:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:14:56.958864:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:14:57.688870:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:15:07.363668:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:15:16.516377:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:15:17.265380:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:15:26.798026:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:15:27.516950:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:15:36.788765:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:15:37.535766:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:15:46.918196:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:15:47.617411:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:15:56.572209:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:15:57.489193:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:16:06.562473:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:16:07.764471:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:16:16.739857:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:16:17.427399:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error at 2021-05-25 17:16:49.802349:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:16:50.450039:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:16:59.724133:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:17:00.490860:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:17:10.486709:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:17:11.490713:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:17:19.588373:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:17:20.308372:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error at 2021-05-25 17:17:54.802748:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:17:55.554200:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:18:04.924111:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:18:05.653069:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:18:14.942406:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:18:15.651403:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error at 2021-05-25 17:18:54.392406:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:18:55.104760:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:19:04.554530:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:19:05.794652:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:19:14.443216:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:19:15.705732:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:19:24.417084:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:19:25.093172:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:19:34.424402:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:19:35.124404:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:19:44.497483:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:19:45.137484:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:19:54.491469:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:19:55.274432:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:20:04.858521:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:20:05.711520:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:20:14.703612:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:20:15.486123:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:20:24.487305:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:20:25.199979:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:20:34.567640:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:20:35.347687:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'


Logs new start

New error at 2021-05-25 17:21:07.988737:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:21:09.396787:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:21:18.974215:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:21:19.669083:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'

New error at 2021-05-25 17:21:28.099041:
type - <class 'ValueError'>, name - autoRemoveRequest.py, line - 31, error - list.remove(x): x not in list

New error at 2021-05-25 17:21:28.802045:
type - <class 'KeyError'>, name - autoRemoveRequest.py, line - 22, error - 'thumbnail'
